version: 1

project_name: meltcd

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
      - MELTCD_HOST=0.0.0.0
    ldflags:
      - -s -w -X github.com/kunalsin9h/meltcd/version.Version={{ .Version }}
    goos:
      - linux
      - windows
      - darwin

    goarch:
      - amd64
      - arm64

    goarm:
      - "7"
release:
  draft: true
  github:
    owner: kunalsin9h
    name: meltcd
  name_template: "{{.ProjectName}} v{{.Version}}"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_{{ .Version }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - CHANGELOG*

checksum:
  name_template: "checksums.txt"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ui:"
      - "^examples:"
