name: Test & Build

on:
  push:
    branches:
      - "main"
  pull_request:

jobs:
  frontend-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: install frontend dependencies
        run: pnpm --prefix=./ui install
      - name: lint frontend
        run: pnpm --prefix=./ui lint

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.54

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: "1.21"
          cache: false
      - name: Run go test
        run: go test -v ./...

  build:
    needs: [frontend-lint, lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: build docker image
        run: |
          docker build -t meltred/meltcd:head .

      - name: publish docker image
        if: github.ref == 'refs/heads/main'
        run: |
          echo ${{ secrets.DOCKER_HUB }} | docker login -u "meltred" --password-stdin
          docker push meltred/meltcd:head

          docker logout

          echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u "kunalsin9h" --password-stdin
          docker image tag meltred/meltcd:head  ghcr.io/meltred/meltcd:head
          docker push ghcr.io/meltred/meltcd:head
